os: linux

language: php

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - COMPOSER_ARGS="--no-interaction"
    - COVERAGE_DEPS="php-coveralls/php-coveralls"

jobs:
  include:
    - php: '7.2'
      env:
        - DEPS=lowest
    - php: '7.2'
      env:
        - DEPS=locked
        - CS_CHECK=true
        - STATIC_ANALYSIS=true
    - php: '7.2'
      env:
        - DEPS=latest
    - php: '7.3'
      env:
        - DEPS=lowest
    - php: '7.3'
      env:
        - DEPS=locked
    - php: '7.3'
      env:
        - DEPS=latest

before_install:
  - composer self-update

install:
  - travis_retry composer install $COMPOSER_ARGS
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry composer require --dev $COMPOSER_ARGS $COVERAGE_DEPS ; fi
  - stty cols 120 && composer show

script:
  - if [[ $STATIC_ANALYSIS == 'true' ]]; then composer analyse ; fi
  - if [[ $CS_CHECK == 'true' ]]; then composer cs-check ; fi

notifications:
  email: false
