version: '3.7'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

services:
  workspace:
    image: ${COMPOSE_PROJECT_NAME}/workspace
    build:
      context: .
      dockerfile: ./workspace/Dockerfile
      args:
        - TZ=${TIMEZONE}
    volumes:
      - ../:/app
    tty: true
    networks:
      - backend