version: '3.7'

networks:
  backend:
    driver: ${NETWORKS_DRIVER-bridge}

services:
  workspace:
    image: par/core/workspace
    build:
      context: .
      dockerfile: .docker/workspace/Dockerfile
      args:
        - TARGET_PHP_VERSION=${PHP_VERSION-7.4}
        - TZ=${TIMEZONE-UTC}
    volumes:
      - .:/app
    tty: true
    networks:
      - backend
  phpdoc:
    image: alexbrouwer/phpdoc:latest
    user: 1000:1000
    volumes:
      - .:/data
    tty: true
    networks:
      - backend