version: '3.7'

networks:
  backend:
    driver: ${NETWORKS_DRIVER-bridge}

services:
  workspace:
      image: par/core/workspace
    build:
      context: .
      dockerfile: .docker/workspace/Dockerfile
      args:
          - TZ=${TIMEZONE-UTC}
    volumes:
        - .:/app
    tty: true
    networks:
      - backend